// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tryskxsqfbzozhixozuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyeXNreHNxZmJ6b3poaXhvenVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NzMxMTksImV4cCI6MjA1OTU0OTExOX0.-WBBBWvePgNpB9iLnSJ2TyJUMIQ99LbAX5r7ZjNCyNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);